/**
 * Generates OLD_VS_NEW.md from the live engine.
 *
 * The table is written by a test rather than kept by hand so it can never drift
 * from the code. If the config changes, the evidence changes with it.
 *
 * Two old models are compared, because the product shipped both:
 *   Old A, the per-payment rule: 30% of revenue excluding VAT. This is what the
 *          tool actually told most people, and it ignores costs entirely.
 *   Old B, the guided estimate: 30% of profit, plus Zvw shown separately. Closer
 *          to right, but still flat where the real system is progressive and
 *          still blind to deductions and credits.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { formatEuroExact, toCents, type Cents } from "@/lib/domain/money";
import { calculateTaxReserve } from "@/lib/tax/engine";
import {
  buildComparisonRows,
  HYBRID_WITHHELD,
  type ComparisonRow,
} from "@/lib/tax/oldVsNew";

function direction(delta: number): string {
  if (delta === 0) return "exact";
  const size = formatEuroExact(Math.abs(delta) as Cents);
  return delta > 0 ? `over by ${size}` : `under by ${size}`;
}

function euro(cents: Cents | number): string {
  return formatEuroExact(cents as Cents);
}

function renderMarkdown(rows: ComparisonRow[]): string {
  const lines: string[] = [];

  lines.push("# The old 30% model versus the real numbers");
  lines.push("");
  lines.push(
    "Generated by `lib/tax/oldVsNew.test.ts` from the live engine. Do not edit by hand; it is rewritten every test run."
  );
  lines.push("");
  lines.push("All figures are for the 2026 tax year, a taxpayer under AOW age, config `nl-2026.1`.");
  lines.push("");

  lines.push("## The two old models");
  lines.push("");
  lines.push(
    "**Old A, the per-payment rule.** 30% of revenue excluding VAT. This is the number the tool put in front of most people. It taxes revenue, so it punishes anyone with costs."
  );
  lines.push("");
  lines.push(
    "**Old B, the guided estimate.** 30% of profit, plus Zvw as a separate line. Better, but still flat where Box 1 is progressive, and blind to the zelfstandigenaftrek, the MKB-winstvrijstelling and both heffingskortingen."
  );
  lines.push("");
  lines.push("**New.** The engine: real brackets, real deductions, real credits, Zvw with its own capped base.");
  lines.push("");

  lines.push("## Comparison");
  lines.push("");
  lines.push(
    "| # | Case | Revenue | Profit | Old A (30% of revenue) | Old B (30% of profit + Zvw) | New (engine) | Old A error | Old B error |"
  );
  lines.push("|---|---|---:|---:|---:|---:|---:|---|---|");
  for (const row of rows) {
    lines.push(
      `| ${row.testCase.id} | ${row.testCase.name} | ${euro(toCents(row.testCase.revenueExVat))} | ${euro(toCents(row.profit))} | ${euro(row.oldA)} | ${euro(row.oldB)} | ${euro(row.actual)} | ${direction(row.deltaA)} | ${direction(row.deltaB)} |`
    );
  }
  lines.push("");

  lines.push("## Case 8, with the loonheffing filled in");
  lines.push("");
  const hybrid = calculateTaxReserve({
    taxYear: 2026,
    country: "NL",
    projectedAnnualProfit: 20_000,
    ytdReserved: 0,
    meetsHoursCriterion: true,
    isStarter: false,
    otherIncome: 30_000,
    otherIncomeTaxWithheld: HYBRID_WITHHELD,
  });
  const hybridRow = rows.find((r) => r.testCase.id === 8)!;
  lines.push(
    `Case 8 above assumes nothing was entered for tax the employer already withheld, which is the cautious reading. Enter a realistic ${euro(toCents(HYBRID_WITHHELD))} of loonheffing on the ${euro(toCents(30_000))} salary and the figure drops from ${euro(hybridRow.actual)} to ${euro(hybrid.totalLiability)}.`
  );
  lines.push("");
  lines.push(
    `The Zvw part is unchanged at ${euro(hybrid.zvw)}, because Zvw here is charged on business profit only. Only the income tax moves.`
  );
  lines.push("");
  lines.push(
    `Either way the old per-payment rule under-reserves this person, because it only ever sees the ${euro(toCents(20_000))} of freelance revenue and never the salary that pushes that profit into a higher bracket. Against the corrected figure it is still ${direction(hybridRow.oldA - hybrid.totalLiability)}.`
  );
  lines.push("");

  lines.push("## What the errors mean");
  lines.push("");
  for (const row of rows) {
    lines.push(`**${row.testCase.id}. ${row.testCase.name}.** ${row.testCase.note}`);
    lines.push("");
    lines.push(
      `Old A said ${euro(row.oldA)}, old B said ${euro(row.oldB)}, the real figure is ${euro(row.actual)}. ` +
        `Against the per-payment rule that is ${direction(row.deltaA)}.`
    );
    lines.push("");
  }

  const worstOver = rows.reduce((a, b) => (b.deltaA > a.deltaA ? b : a));
  const worstUnder = rows.reduce((a, b) => (b.deltaA < a.deltaA ? b : a));

  lines.push("## The headline");
  lines.push("");
  lines.push(
    `The per-payment rule is wrong in both directions. Its worst over-reserve is case ${worstOver.testCase.id} (${worstOver.testCase.name}), ${direction(worstOver.deltaA)}. Its worst under-reserve is case ${worstUnder.testCase.id} (${worstUnder.testCase.name}), ${direction(worstUnder.deltaA)}.`
  );
  lines.push("");
  lines.push(
    "Over-reserving is not harmless. Money parked against a bill that will never arrive is money not paid to yourself, and for a freelancer with irregular income that is the difference between a lean month and a fine one. Under-reserving is worse: it is a bill you cannot pay."
  );
  lines.push("");
  lines.push(
    "The single largest driver of the difference at low and middle incomes is the heffingskortingen. The old model ignored them entirely. On case 1 they cancel the income tax outright, leaving only Zvw, which the flat model had folded into one number and hidden."
  );
  lines.push("");

  return lines.join("\n");
}

describe("old versus new", () => {
  const rows = buildComparisonRows();

  it("shows the hybrid case both with and without loonheffing", () => {
    const withheld = calculateTaxReserve({
      taxYear: 2026,
      country: "NL",
      projectedAnnualProfit: 20_000,
      ytdReserved: 0,
      meetsHoursCriterion: true,
      isStarter: false,
      otherIncome: 30_000,
      otherIncomeTaxWithheld: HYBRID_WITHHELD,
    });
    const row = rows.find((r) => r.testCase.id === 8)!;
    expect(row.actual - withheld.totalLiability).toBe(toCents(HYBRID_WITHHELD));
    // The old flat rule under-reserves this person either way, because it only
    // ever sees the €20.000 of freelance revenue and never the salary that
    // pushes that profit into a higher bracket. Counting the loonheffing
    // narrows the gap; it does not close it.
    expect(row.deltaA).toBeLessThan(0);
    expect(row.oldA - withheld.totalLiability).toBeLessThan(0);
    expect(Math.abs(row.oldA - withheld.totalLiability)).toBeLessThan(
      Math.abs(row.deltaA)
    );
  });

  it("writes OLD_VS_NEW.md", () => {
    const path = join(process.cwd(), "OLD_VS_NEW.md");
    writeFileSync(path, renderMarkdown(rows), "utf8");
    expect(rows).toHaveLength(10);
  });

  it("shows the per-payment rule over-reserving badly on a high-cost year", () => {
    // Case 9: €80.000 revenue, €35.000 costs. 30% of revenue ignores the costs.
    const row = rows.find((r) => r.testCase.id === 9)!;
    expect(row.oldA).toBe(toCents(24_000));
    expect(row.deltaA).toBeGreaterThan(toCents(15_000));
  });

  it("shows the per-payment rule over-reserving on a low-profit starter year", () => {
    const row = rows.find((r) => r.testCase.id === 1)!;
    expect(row.deltaA).toBeGreaterThan(0);
  });

  it("shows the flat model under-reserving at high profit", () => {
    // At €95.000 the top bracket and the rate adjustment both bite, and 30%
    // does not cover them.
    const row = rows.find((r) => r.testCase.id === 7)!;
    expect(row.deltaA).toBeLessThan(0);
    expect(row.deltaB).toBeLessThan(0);
  });

  it("charges nothing in a loss year, where the old model still charged", () => {
    const row = rows.find((r) => r.testCase.id === 10)!;
    expect(row.actual).toBe(0);
    expect(row.oldA).toBe(toCents(4500));
  });
});
